accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import CustomLoginForm

urlpatterns = [
   # post views
   # path('login/', views.user_login, name='login'),
   path('login/', auth_views.LoginView.as_view(authentication_form=CustomLoginForm), name='login'),
   path('logout/', auth_views.LogoutView.as_view(), name='logout'),
   path('register/', views.register, name='register'),

]

mine_mgt/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'mine_mgt'

urlpatterns = [
   # post views
   path('', views.dashboard, name='dashboard'),
   path('payments/', views.payments, name='payments'),
   path('claim/<int:id>', views.claim_detail, name='claim_detail'),
   path('application/<int:id>', views.claim_application, name='claim_application'),
   path('accept/<int:id>', views.accept, name='accept'),
   path('apply/', views.apply, name='apply'),
   path('forfeited/<int:id>', views.forfeited, name='forfeited'),

   path('apply_forfeited/<int:id>', views.apply_forfeited, name='apply_forfeited'),
   path('add_payment/<int:id>', views.add_payment, name='add_payment'),
   path('claims_on_offer/', views.claims_on_offer, name='claims_on_offer'),


]

mining_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mine_mgt.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mine_mgt/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from accounts.models import User


class ForfeitedManager(models.Manager):
    def get_queryset(self):
        return super(ForfeitedManager,
                     self).get_queryset() \
            .filter(status='forfeit')


class PendingApprovalManager(models.Manager):
    def get_queryset(self):
        return super(PendingApprovalManager,
                     self).get_queryset() \
            .filter(status='pending_approval')


class ActiveManager(models.Manager):
    def get_queryset(self):
        return super(ActiveManager,
                     self).get_queryset() \
            .filter(status='active')


# # Create your models here.
# class Mine(models.Model):
#     user = models.OneToOneField(User, related_name='mine', on_delete=models.CASCADE)
#     name = models.CharField(max_length=250)
#     created = models.DateTimeField(default=timezone.now)
#     balance = models.CharField(max_length=250)
#
#     class Meta:
#         ordering = ('-name',)
#
#     def __str__(self):
#         return self.name


class Claim(models.Model):
    STATUS_CHOICES = (
        ('pending_approval', 'Pending Approval'),
        ('forfeit', 'Forfeited'),
        ('active', 'Active')
    )
    applicant = models.ForeignKey(User, related_name='claims', on_delete=models.CASCADE)
    location = models.CharField(max_length=250)
    address = models.CharField(max_length=250)
    size_approximation = models.CharField(max_length=250)
    date_applied = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=30,
                              choices=STATUS_CHOICES,
                              default='pending_approval')
    created = models.DateTimeField(default=timezone.now)
    objects = models.Manager()  # The default manager.
    forfeited = ForfeitedManager()  # Our custom manager.
    pending_approval = PendingApprovalManager()  # Our custom manager.
    active = ActiveManager()  # Our custom manager.

    class Meta:
        ordering = ('-created',)


class Proof(models.Model):
    image = models.ImageField(upload_to='images', blank=True)
    uploaded_by = models.ForeignKey(User, related_name='proof_of_payment', on_delete=models.CASCADE)
    is_processeed = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-created',)


class Payment(models.Model):
    amount = models.CharField(max_length=250)
    reason = models.CharField(max_length=250)
    user = models.ForeignKey(User, related_name='payments', on_delete=models.CASCADE, null=True)
    proof = models.ForeignKey(Proof, related_name='payment', on_delete=models.CASCADE, null=True)
    is_processeed = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-created',)

mine_mgt/forms.py
from django import forms
from .models import Proof, Claim, Payment

class ProofForm(forms.ModelForm):

    class Meta:
        model = Proof
        fields = ('image',)


class ClaimForm(forms.ModelForm):
    location = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Harare, Zimbabwe',
        }
    ))

    address = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': '21 Hillcrest Rd',
        }
    ))

    size_approximation = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': '300Ha',
        }
    ))



    class Meta:
        model = Claim
        fields = ('location', 'address', 'size_approximation')



class PaymentForm(forms.ModelForm):
    amount = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': '230',
        }
    ))

    reason = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Monthly Payment',
        }
    ))

    class Meta:
        model = Payment
        fields = ('amount', 'reason')

mine_mgt/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from .models import Claim, Proof, Payment
from accounts.models import User
from .forms import ProofForm, ClaimForm, PaymentForm


@login_required
def dashboard(request):
    forfeited_claims = Claim.forfeited.all()
    if request.user.is_mine:
        active_claims = Claim.active.filter(applicant=request.user)
        pending_claims = Claim.pending_approval.filter(applicant=request.user)
        user = get_object_or_404(User, id=request.user.id)
        context = {
            'active_claims': active_claims,
            'pending_claims': pending_claims,
            'user': user,
            'forfeited_claims': forfeited_claims
        }
        return render(request, 'mine_mgt/miner/dashboard.html', context)
    else:
        active_claims = Claim.active.filter()
        pending_claims = Claim.pending_approval.filter()
        context = {
            'active_claims': active_claims,
            'pending_claims': pending_claims,
            'forfeited_claims': forfeited_claims
        }
        return render(request, 'mine_mgt/admin/dashboard.html', context)


@login_required
def payments(request):
    if request.user.is_mine:
        if request.method == 'POST':
            form = ProofForm(data=request.POST, files=request.FILES)
            if form.is_valid():
                new_proof = form.save(commit=False)
                new_proof.uploaded_by = get_object_or_404(User, id=request.user.id)
                new_proof.save()
                return redirect('mine_mgt:payments')
        else:
            form = ProofForm()
        payments = Payment.objects.filter(user=request.user)
        proofs = Proof.objects.filter(uploaded_by=request.user)
        context = {
            'payments': payments,
            'proofs': proofs,
            'form': form
        }
        return render(request, 'mine_mgt/miner/payments.html', context)
    else:
        payments = Payment.objects.filter()
        proofs = Proof.objects.exclude(is_processeed=True)
        context = {
            'payments': payments,
            'proofs': proofs,
        }
        return render(request, 'mine_mgt/admin/payments.html', context)



@login_required
def claim_detail(request, id):
    if request.user.is_administrator:
        claim = get_object_or_404(Claim, id=id)
        proofs = Proof.objects.filter(uploaded_by=request.user)
        payments = Payment.objects.filter(user=request.user)
        context = {
            'claim': claim,
            'proofs': proofs,
            'payments': payments
        }
        return render(request, 'mine_mgt/admin/claim_detail.html', context)
    else:
        return redirect('mine_mgt:dashboard')


@login_required
def claim_application(request, id):
    if request.user.is_administrator:
        claim = get_object_or_404(Claim, id=id)
        pending_claims = Claim.pending_approval.exclude(id=id)
        context = {
            'claim': claim,
            'pending_claims': pending_claims
        }
        return render(request, 'mine_mgt/admin/claim_application.html', context)
    else:
        return redirect('mine_mgt:dashboard')

@login_required
def accept(request, id):
    claim = get_object_or_404(Claim, id=id)
    claim.status = 'active'
    claim.save()
    return redirect('mine_mgt:dashboard')

@login_required
def apply(request):
    claims = Claim.forfeited.all()
    if request.method == 'POST':
        form = ClaimForm(data=request.POST)
        if form.is_valid():
            new_claim = form.save(commit=False)
            new_claim.applicant = get_object_or_404(User, id=request.user.id)
            new_claim.save()
            return redirect('mine_mgt:dashboard')
    else:
        form = ClaimForm()

    context = {
        'claims': claims,
        'form': form
    }
    return render(request, 'mine_mgt/miner/apply.html', context)


@login_required
def apply_forfeited(request, id):
    claim = Claim.forfeited.get(id=id)
    claim.applicant = get_object_or_404(User, id=request.user.id)
    claim.status = 'pending_approval'
    claim.save()
    return redirect('mine_mgt:dashboard')


@login_required
def forfeited(request, id):
    claim = Claim.forfeited.get(id=id)
    claims = Claim.forfeited.exclude(id=id)
    context = {
        'claim': claim,
        'claims': claims
    }

    return render(request, 'mine_mgt/miner/forfeited.html', context)



@login_required
def add_payment(request, id):
    proof = get_object_or_404(Proof, id=id)
    user = proof.uploaded_by
    if request.method == 'POST':
        form = PaymentForm(data=request.POST)
        if form.is_valid():
            new_payment = form.save(commit=False)
            new_payment.user = get_object_or_404(User, id=proof.uploaded_by.id)
            new_payment.proof = proof
            new_payment.is_processeed = True
            print('434343434343434333334343', new_payment)
            new_payment.save()
            proof.is_processeed = True
            proof.save()
            return redirect('mine_mgt:dashboard')
    else:
        form = PaymentForm()

    context = {
        'proof': proof,
        'form': form,
        'user': user
    }

    return render(request, 'mine_mgt/admin/add_payment.html', context)


@login_required
def claims_on_offer(request):
    claims = Claim.forfeited.all()

    context = {
        'claims': claims
    }

    return render(request, 'mine_mgt/miner/claims_on_offer.html', context)

mine_mgt/templates/mine_mgt/miner/apply.html
{% extends "mine_mgt/base.html" %}

{% block title %}Payments{% endblock %}


{% block content %}



<div class="container-fluid py-4">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header pb-0">
          <div class="d-flex align-items-center">
            <p class="mb-0">Claim Application</p>
          </div>
        </div>
          <form action="" method="post">
                <div class="card-body">
                  <p class="text-uppercase text-sm">User Information</p>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="example-text-input" class="form-control-label">Username</label>
                        <input class="form-control" disabled type="text" value="{{ user.username }}">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="example-text-input" class="form-control-label">Email address</label>
                        <input class="form-control" disabled type="email" value="{{ user.email }}">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="example-text-input" class="form-control-label">First name</label>
                        <input class="form-control" disabled type="text" value="{{ user.first_name }}">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="example-text-input" class="form-control-label">Last name</label>
                        <input class="form-control" disabled type="text" value="{{ user.last_name }}">
                      </div>
                    </div>
                  </div>
                  <hr class="horizontal dark">
                  <p class="text-uppercase text-sm">Claim Information</p>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="example-text-input" class="form-control-label">Address</label>
                        {{ form.address }}
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="form-group">
                        <label for="example-text-input" class="form-control-label">Location</label>
                        {{ form.location }}
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="form-group">
                        <label for="example-text-input" class="form-control-label">Country</label>
                        <input class="form-control" disabled type="text" value="Zimbabwe">
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="form-group">
                        <label for="example-text-input" class="form-control-label">Size Approximation</label>
                        {{ form.size_approximation }}
                      </div>
                    </div>
                      {% csrf_token %}
                      <div class="d-flex align-items-center pt-3">
                        <button type="submit" class="btn btn-primary btn-sm ms-auto">Submit</button>
                      </div>
                  </div>

                </div>
              </form>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card" style="height: 320px;">
        <div class="card-header pb-0 p-3">
          <h6 class="mb-0">Claims on Offer ({{claims.count}})</h6>
        </div>
        <div class="card-body p-3">
          <ul class="list-group">

               {% for claim in claims %}
                     <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                        <div class="d-flex align-items-center">
                          <div class="icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center">
                            <i class="ni ni-tag text-white opacity-10"></i>
                          </div>
                          <div class="d-flex flex-column">
                            <h6 class="mb-1 text-dark text-sm">{{ claim.location }}</h6>
                            <span class="text-xs">{{ claim.address }} <span class="font-weight-bold">15 open</span></span>
                          </div>
                        </div>
                        <div class="d-flex">
                          <a href="{% url 'mine_mgt:forfeited' claim.id %}" class="btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto"><i class="ni ni-bold-right" aria-hidden="true"></i></a>
                        </div>
                      </li>
               {% endfor %}

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mine_mgt/templates/mine_mgt/miner/claims_on_offer.html
{% extends "mine_mgt/base.html" %}

{% block title %}Payments{% endblock %}


{% block content %}



<div class="container-fluid py-4">
  <div class="row">

    <div class="col-md-12">
      <div class="card" style="height: 320px;">
        <div class="card-header pb-0 p-3">
          <h6 class="mb-0">Claims on Offer ({{claims.count}})</h6>
        </div>
        <div class="card-body p-3">
          <ul class="list-group">

               {% for claim in claims %}

                  <a href="{% url 'mine_mgt:forfeited' claim.id %}">
                      <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                        <div class="d-flex align-items-center">
                          <div class="icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center">
                            <i class="ni ni-tag text-white opacity-10"></i>
                          </div>
                          <div class="d-flex flex-column">
                            <h6 class="mb-1 text-dark text-sm">{{ claim.location }}</h6>
                            <span class="text-xs">{{ claim.address }} <span class="font-weight-bold">15 open</span></span>
                          </div>
                        </div>
                        <div class="d-flex">
                          <a href="{% url 'mine_mgt:forfeited' claim.id %}" class="btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto"><i class="ni ni-bold-right" aria-hidden="true"></i></a>
                        </div>
                      </li>
                  </a>
               {% endfor %}

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mine_mgt/templates/mine_mgt/miner/dashboard.html
{% extends "mine_mgt/base.html" %}
{% block title %}Dashboard{% endblock %}


{% block content %}

<div class="container-fluid py-4">
      <div class="row">
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
          <div class="card">
            <a href="{% url 'mine_mgt:payments' %}">
              <div class="card-body p-3">
                <div class="row">
                  <div class="col-8">
                    <div class="numbers">
                      <p class="text-sm mb-0 text-uppercase font-weight-bold">Payments</p>
                      <h5 class="font-weight-bolder pt-3">
                        ${{ user.balance }}
                      </h5>

                    </div>
                  </div>
                  <div class="col-4 text-end">
                    <div class="icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle">
                      <i class="ni ni-money-coins text-lg opacity-10" aria-hidden="true"></i>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
          <div class="card">
            <a href="">
              <div class="card-body p-3">
                <div class="row">
                  <div class="col-8">
                    <div class="numbers">
                      <p class="text-sm mb-0 text-uppercase font-weight-bold">Monthly labor Returns</p>
                      <h5 class="font-weight-bolder pt-3">
                        0
                      </h5>

                    </div>
                  </div>
                  <div class="col-4 text-end">
                    <div class="icon icon-shape bg-gradient-danger shadow-danger text-center rounded-circle">
                      <i class="ni ni-world text-lg opacity-10" aria-hidden="true"></i>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
          <div class="card">
            <a href="">
              <div class="card-body p-3">
                <div class="row">
                  <div class="col-8">
                    <div class="numbers">
                      <p class="text-sm mb-0 text-uppercase font-weight-bold">Annual Inspections </p>
                      <h5 class="font-weight-bolder pt-3">
                        0
                      </h5>

                    </div>
                  </div>
                  <div class="col-4 text-end">
                    <div class="icon icon-shape bg-gradient-success shadow-success text-center rounded-circle">
                      <i class="ni ni-paper-diploma text-lg opacity-10" aria-hidden="true"></i>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6">
          <div class="card">
            <a href="{% url 'mine_mgt:claims_on_offer' %}">
              <div class="card-body p-3">
                <div class="row">
                  <div class="col-8">
                    <div class="numbers">
                      <p class="text-sm mb-0 text-uppercase font-weight-bold">Claims on offer</p>
                      <h5 class="font-weight-bolder pt-3">
                        {{ forfeited_claims.count }}
                      </h5>

                    </div>
                  </div>
                  <div class="col-4 text-end">
                    <div class="icon icon-shape bg-gradient-warning shadow-warning text-center rounded-circle">
                      <i class="ni ni-cart text-lg opacity-10" aria-hidden="true"></i>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>

      <div class="row mt-4">
        <div class="col-lg-7 mb-lg-0 mb-4">
          <div class="card " style="height: 320px;">
            <div class="card-header pb-0 p-3">
              <!--<div class="d-flex justify-content-between">-->
                <!--<h6 class="mb-2">Mine Claims ({{active_claims.count}})</h6>-->
              <!--</div>-->
              <!--<div class="col-6 text-end">-->
                <!--<button class="btn btn-outline-primary btn-sm mb-0">View All</button>-->
              <!--</div>-->
              <div class="row pb-4">
                    <div class="col-6 d-flex align-items-center">
                      <h6 class="mb-0">Mine Claims ({{active_claims.count}})</h6>
                    </div>
                    <div class="col-6 text-end">
                      <a href="{% url 'mine_mgt:apply' %}" class="btn btn-outline-primary btn-sm mb-0">Apply</a>
                    </div>
              </div>
            </div>
            <div class="table-responsive">
              <table class="table align-items-center ">
                <tbody>

                    {% for claim in active_claims %}
                         <tr>
                              <td class="w-30">
                                <div class="d-flex px-2 py-1 align-items-center">

                                  <div class="ms-4">
                                    <p class="text-xs font-weight-bold mb-0">Location:</p>
                                    <h6 class="text-sm mb-0">{{ claim.location }}</h6>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <div class="text-center">
                                  <p class="text-xs font-weight-bold mb-0">Address:</p>
                                  <h6 class="text-sm mb-0">{{ claim.address }}</h6>
                                </div>
                              </td>
                              <td>
                                <div class="text-center">
                                  <p class="text-xs font-weight-bold mb-0">Monthly Returns:</p>
                                  <h6 class="text-sm mb-0">$230,900</h6>
                                </div>
                              </td>
                              <td>
                                <div class="text-center">
                                  <a href="" class="btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto"><i class="ni ni-bold-right" aria-hidden="true"></i></a>
                                </div>
                              </td>

                         </tr>

                  {% endfor %}




                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-lg-5">
          <div class="card" style="height: 320px;">
            <div class="card-header pb-0 p-3">
              <h6 class="mb-0">Applications ({{pending_claims.count}})</h6>
            </div>
            <div class="card-body p-3">
              <ul class="list-group">

                   {% for claim in pending_claims %}
                         <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                            <div class="d-flex align-items-center">
                              <div class="icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center">
                                <i class="ni ni-tag text-white opacity-10"></i>
                              </div>
                              <div class="d-flex flex-column">
                                <h6 class="mb-1 text-dark text-sm">{{ claim.location }}</h6>
                                <span class="text-xs">{{ claim.address }} <span class="font-weight-bold">15 open</span></span>
                              </div>
                            </div>
                            <div class="d-flex">
                              <a href="" class="btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto"><i class="ni ni-bold-right" aria-hidden="true"></i></a>
                            </div>
                          </li>
                   {% endfor %}

              </ul>
            </div>
          </div>
        </div>
      </div>

    </div>








{% endblock %}

mine_mgt/templates/mine_mgt/miner/forfeited.html
{% extends "mine_mgt/base.html" %}

{% block title %}Payments{% endblock %}


{% block content %}



<div class="container-fluid py-4">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header pb-0">
          <div class="d-flex align-items-center">
            <p class="mb-0">Claim Application</p>
          </div>
        </div>
        <div class="card-body">
          <p class="text-uppercase text-sm">User Information</p>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="example-text-input" class="form-control-label">Username</label>
                <input class="form-control" disabled type="text" value="{{ user.username }}">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="example-text-input" class="form-control-label">Email address</label>
                <input class="form-control" disabled type="email" value="{{ user.email }}">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="example-text-input" class="form-control-label">First name</label>
                <input class="form-control" disabled type="text" value="{{ user.first_name }}">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="example-text-input" class="form-control-label">Last name</label>
                <input class="form-control" disabled type="text" value="{{ user.last_name }}">
              </div>
            </div>
          </div>
          <hr class="horizontal dark">
          <p class="text-uppercase text-sm">Claim Information</p>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="example-text-input" class="form-control-label">Address</label>
                  <input class="form-control" disabled type="text" value="{{ claim.address }}">
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="example-text-input" class="form-control-label">Location</label>
                <input class="form-control" disabled type="text" value="{{ claim.location }}">
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="example-text-input" class="form-control-label">Country</label>
                <input class="form-control" disabled type="text" value="Zimbabwe">
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="example-text-input" class="form-control-label">Size Approximation</label>
                <input class="form-control" disabled type="text" value="{{ claim.size_approximation }}">
              </div>
            </div>
              <div class="d-flex align-items-center pt-3">
                <a href="{% url 'mine_mgt:apply_forfeited' claim.id%}" class="btn btn-primary btn-sm ms-auto">Submit</a>
              </div>
          </div>

        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card" style="height: 320px;">
        <div class="card-header pb-0 p-3">
          <h6 class="mb-0">Claims on Offer ({{claims.count}})</h6>
        </div>
        <div class="card-body p-3">
          <ul class="list-group">

               {% for claim in claims %}
                     <li class="list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg">
                        <div class="d-flex align-items-center">
                          <div class="icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center">
                            <i class="ni ni-tag text-white opacity-10"></i>
                          </div>
                          <div class="d-flex flex-column">
                            <h6 class="mb-1 text-dark text-sm">{{ claim.location }}</h6>
                            <span class="text-xs">{{ claim.address }} <span class="font-weight-bold">15 open</span></span>
                          </div>
                        </div>
                        <div class="d-flex">
                          <a href="{% url 'mine_mgt:forfeited' claim.id %}" class="btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto"><i class="ni ni-bold-right" aria-hidden="true"></i></a>
                        </div>
                      </li>
               {% endfor %}

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}